package forme;

import domen.Angazovanje;
import domen.Projekat;
import forme.projekti.DodajProjekatForma;
import forme.projekti.ObrisiProjekatForma;
import forme.zaposleni.DodajZaposlenogForma;
import forme.zaposleni.IzmeniZaposlenogForma;
import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import kontroler.KlijentKontrolerAdministrator;
import kontroler.KlijentKontrolerAngazovanje;
import kontroler.KlijentKontrolerProjekat;
import sesija.Sesija;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.XChartPanel;
/**
 *
 * @author Mihajlo
 */
public class GlavnaForma extends javax.swing.JFrame{

    private XChartPanel<CategoryChart> chartPanel;
    private CategoryChart chart;
    
    private XChartPanel<PieChart> pieChartPanel;
    private PieChart pieChart;
    private javax.swing.JPanel panelZaGrafikone;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() throws Exception {
        initComponents();
        Locale latinica = new Locale.Builder()
                        .setLanguage("sr")
                        .setScript("Latn")
                        .build();

        lokalizacija.JezikMenadzer.setLocale(latinica);
        osveziLokalizaciju();
        this.getContentPane().setLayout(new BorderLayout());
        lblUlogovani.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        this.getContentPane().add(lblUlogovani, BorderLayout.NORTH);
        panelZaGrafikone = new javax.swing.JPanel(new java.awt.GridLayout(1, 2, 10, 0));
        this.getContentPane().add(panelZaGrafikone, BorderLayout.CENTER);
        iscrtajGrafike();
        setLocationRelativeTo(null);
        lblUlogovani.setText("Administrator: " + Sesija.getInstanca().getUlogovani());
        menuAngazovanja.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuZaposleni = new javax.swing.JMenu();
        menuItemDodajZaposlenog = new javax.swing.JMenuItem();
        menuItemIzmeniZaposlenog = new javax.swing.JMenuItem();
        menuProjekti = new javax.swing.JMenu();
        menuItemDodajProjekat = new javax.swing.JMenuItem();
        menuItemObrisiProjekat = new javax.swing.JMenuItem();
        menuAngazovanja = new javax.swing.JMenu();
        btnDodajAngazovanje = new javax.swing.JMenuItem();
        menuItemObrisiAngazovanje = new javax.swing.JMenuItem();
        menuOdjava = new javax.swing.JMenu();
        menuItemOdjaviSe = new javax.swing.JMenuItem();
        jMenuJezik = new javax.swing.JMenu();
        jMenuItemSrpskiLatinica = new javax.swing.JMenuItem();
        jMenuItemSrpskiCirilica = new javax.swing.JMenuItem();
        jMenuItemEnglish = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("jLabel1");

        menuZaposleni.setText("Zaposleni");

        menuItemDodajZaposlenog.setText("Dodavanje");
        menuItemDodajZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDodajZaposlenogActionPerformed(evt);
            }
        });
        menuZaposleni.add(menuItemDodajZaposlenog);

        menuItemIzmeniZaposlenog.setText("Izmena i Brisanje");
        menuItemIzmeniZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIzmeniZaposlenogActionPerformed(evt);
            }
        });
        menuZaposleni.add(menuItemIzmeniZaposlenog);

        jMenuBar1.add(menuZaposleni);

        menuProjekti.setText("Projekti");

        menuItemDodajProjekat.setText("Dodavanje");
        menuItemDodajProjekat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDodajProjekatActionPerformed(evt);
            }
        });
        menuProjekti.add(menuItemDodajProjekat);

        menuItemObrisiProjekat.setText("Izmena i Brisanje");
        menuItemObrisiProjekat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemObrisiProjekatActionPerformed(evt);
            }
        });
        menuProjekti.add(menuItemObrisiProjekat);

        jMenuBar1.add(menuProjekti);

        menuAngazovanja.setText("Angazovanja");

        btnDodajAngazovanje.setText("Dodaj");
        btnDodajAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAngazovanjeActionPerformed(evt);
            }
        });
        menuAngazovanja.add(btnDodajAngazovanje);

        menuItemObrisiAngazovanje.setText("Obriši");
        menuItemObrisiAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemObrisiAngazovanjeActionPerformed(evt);
            }
        });
        menuAngazovanja.add(menuItemObrisiAngazovanje);

        jMenuBar1.add(menuAngazovanja);

        menuOdjava.setText("Odjava");

        menuItemOdjaviSe.setText("Odjavi se");
        menuItemOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOdjaviSeActionPerformed(evt);
            }
        });
        menuOdjava.add(menuItemOdjaviSe);

        jMenuBar1.add(menuOdjava);

        jMenuJezik.setText("Jezik");

        jMenuItemSrpskiLatinica.setText("srpski - latinica");
        jMenuItemSrpskiLatinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSrpskiLatinicaActionPerformed(evt);
            }
        });
        jMenuJezik.add(jMenuItemSrpskiLatinica);

        jMenuItemSrpskiCirilica.setText("српски - ћирилица");
        jMenuItemSrpskiCirilica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSrpskiCirilicaActionPerformed(evt);
            }
        });
        jMenuJezik.add(jMenuItemSrpskiCirilica);

        jMenuItemEnglish.setText("english");
        jMenuItemEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnglishActionPerformed(evt);
            }
        });
        jMenuJezik.add(jMenuItemEnglish);

        jMenuBar1.add(jMenuJezik);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(917, Short.MAX_VALUE)
                .addComponent(lblUlogovani)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUlogovani)
                .addGap(0, 491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOdjaviSeActionPerformed
        try{
            int izbor = JOptionPane.showConfirmDialog(this, lokalizacija.JezikMenadzer.get("odjavaPitanje"), lokalizacija.JezikMenadzer.get("odjava"), JOptionPane.YES_NO_OPTION);

            if (izbor == JOptionPane.YES_OPTION) {
                Sesija.getInstanca().setUlogovani(null);
                KlijentKontrolerAdministrator.getInstanca().logout();
                System.exit(0);
                //new LoginForma().setVisible(true);
            }
            
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuItemOdjaviSeActionPerformed

    private void menuItemDodajZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDodajZaposlenogActionPerformed
        new DodajZaposlenogForma(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemDodajZaposlenogActionPerformed

    private void menuItemDodajProjekatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDodajProjekatActionPerformed
        new DodajProjekatForma(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemDodajProjekatActionPerformed

    private void menuItemObrisiProjekatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemObrisiProjekatActionPerformed
        new ObrisiProjekatForma(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemObrisiProjekatActionPerformed

    private void btnDodajAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAngazovanjeActionPerformed
    }//GEN-LAST:event_btnDodajAngazovanjeActionPerformed

    private void menuItemObrisiAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemObrisiAngazovanjeActionPerformed
    }//GEN-LAST:event_menuItemObrisiAngazovanjeActionPerformed

    private void menuItemIzmeniZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIzmeniZaposlenogActionPerformed
        new IzmeniZaposlenogForma(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemIzmeniZaposlenogActionPerformed

    private void jMenuItemSrpskiLatinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSrpskiLatinicaActionPerformed
        Locale latinica = new Locale.Builder()
                        .setLanguage("sr")
                        .setScript("Latn")
                        .build();

        lokalizacija.JezikMenadzer.setLocale(latinica);
        lokalizacija.JezikMenadzer.setOdabir("srpski - latinica");
        osveziLokalizaciju();
    }//GEN-LAST:event_jMenuItemSrpskiLatinicaActionPerformed

    private void jMenuItemSrpskiCirilicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSrpskiCirilicaActionPerformed
        lokalizacija.JezikMenadzer.setLocale(Locale.of("sr"));
        lokalizacija.JezikMenadzer.setOdabir("srpski - cirilica");
        osveziLokalizaciju();
    }//GEN-LAST:event_jMenuItemSrpskiCirilicaActionPerformed

    private void jMenuItemEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnglishActionPerformed
        lokalizacija.JezikMenadzer.setLocale(Locale.ENGLISH);
        lokalizacija.JezikMenadzer.setOdabir("english");
        osveziLokalizaciju();
    }//GEN-LAST:event_jMenuItemEnglishActionPerformed

    private void osveziLokalizaciju() {
        jMenuJezik.setText(lokalizacija.JezikMenadzer.get("jezik"));
        menuZaposleni.setText(lokalizacija.JezikMenadzer.get("zaposleni"));
        menuProjekti.setText(lokalizacija.JezikMenadzer.get("projekti"));
        menuAngazovanja.setText(lokalizacija.JezikMenadzer.get("angazovanja"));
        menuOdjava.setText(lokalizacija.JezikMenadzer.get("odjava"));
        lblUlogovani.setText(lokalizacija.JezikMenadzer.get("administrator") + ": " + Sesija.getInstanca().getUlogovani());
        menuItemDodajZaposlenog.setText(lokalizacija.JezikMenadzer.get("dodavanje"));
        menuItemIzmeniZaposlenog.setText(lokalizacija.JezikMenadzer.get("izmenaIBrisanje"));
        menuItemDodajProjekat.setText(lokalizacija.JezikMenadzer.get("dodavanje"));
        menuItemObrisiProjekat.setText(lokalizacija.JezikMenadzer.get("izmenaIBrisanje"));
        menuItemOdjaviSe.setText(lokalizacija.JezikMenadzer.get("odjaviSe"));
        if (chart != null && chartPanel != null) {
            chart.setTitle(lokalizacija.JezikMenadzer.get("brojZaposlenihPoProjektu"));
            chart.setXAxisTitle(lokalizacija.JezikMenadzer.get("projekat"));
            chart.setYAxisTitle(lokalizacija.JezikMenadzer.get("brojZaposlenih"));
            chartPanel.repaint();
        }
        if (pieChart != null && pieChartPanel != null) {
            pieChart.setTitle(lokalizacija.JezikMenadzer.get("stanjeProjekata"));
            pieChartPanel.repaint();
        }
        UIManager.put("OptionPane.yesButtonText", lokalizacija.JezikMenadzer.get("da"));
        UIManager.put("OptionPane.noButtonText", lokalizacija.JezikMenadzer.get("ne"));
        UIManager.put("OptionPane.okButtonText", lokalizacija.JezikMenadzer.get("ok"));
        UIManager.put("OptionPane.cancelButtonText", lokalizacija.JezikMenadzer.get("cancel"));
    }
    
    public void iscrtajGrafike() throws Exception{
        LinkedList<Angazovanje> listaSvihAngazovanja = KlijentKontrolerAngazovanje.getInstanca().vratiAngazovanja();
        LinkedList<Projekat> listaSvihProjekata = KlijentKontrolerProjekat.getInstanca().vratiProjekte(false);

        Map<Projekat, Integer> statistikaZaposleniNaProjektima = new java.util.TreeMap<>((p1, p2) -> Integer.compare(p1.getProjekatId(), p2.getProjekatId()));
        for (Angazovanje a : listaSvihAngazovanja) {
            if (a.getProjekat() != null && !a.getDaLiJeObrisan()) {
                Projekat p = a.getProjekat();
                statistikaZaposleniNaProjektima.put(p, statistikaZaposleniNaProjektima.getOrDefault(p, 0) + 1);
            }
        }

        java.util.List<String> naziviProjekata = new java.util.ArrayList<>();
        java.util.List<Number> brojZaposlenih = new java.util.ArrayList<>();
        
        for (Map.Entry<Projekat, Integer> entry : statistikaZaposleniNaProjektima.entrySet()) {
            naziviProjekata.add(entry.getKey().getNazivProjekta());
            brojZaposlenih.add(entry.getValue());
        }

        chart = new CategoryChartBuilder()
                .width(800)
                .height(500)
                .title(lokalizacija.JezikMenadzer.get("brojZaposlenihPoProjektu"))
                .xAxisTitle(lokalizacija.JezikMenadzer.get("projekat"))
                .yAxisTitle(lokalizacija.JezikMenadzer.get("brojZaposlenih"))
                .build();

        chart.getStyler().setLegendVisible(false);
        chart.getStyler().setYAxisDecimalPattern("#");

        if (!naziviProjekata.isEmpty()) {
            chart.addSeries("Zaposleni", naziviProjekata, brojZaposlenih);
        }
       
        
        Map<String, Integer> statistikaStanjaProjekata = new HashMap<>();

        for (Projekat p : listaSvihProjekata) {
            if (p.getStanje() != null) {
                String stanjeNaziv = p.getStanje().toString(); 
                statistikaStanjaProjekata.put(stanjeNaziv, statistikaStanjaProjekata.getOrDefault(stanjeNaziv, 0) + 1);
            }
        }

        pieChart = new PieChartBuilder()
            .width(400)
            .height(500)
            .title(lokalizacija.JezikMenadzer.get("stanjeProjekata"))
            .build();

        pieChart.getStyler().setLegendVisible(false);
        pieChart.getStyler().setLabelsVisible(true);
        pieChart.getStyler().setLabelType(org.knowm.xchart.style.PieStyler.LabelType.NameAndPercentage);
        pieChart.getStyler().setLabelsDistance(0.6); 
        pieChart.getStyler().setLabelsFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));

        for (Map.Entry<String, Integer> entry : statistikaStanjaProjekata.entrySet()) {
            pieChart.addSeries(entry.getKey(), (Number) entry.getValue());
        }


        panelZaGrafikone.removeAll();

        chartPanel = new XChartPanel<>(chart);
        pieChartPanel = new XChartPanel<>(pieChart);

        panelZaGrafikone.add(chartPanel);
        panelZaGrafikone.add(pieChartPanel);

        this.revalidate();
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDodajAngazovanje;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEnglish;
    private javax.swing.JMenuItem jMenuItemSrpskiCirilica;
    private javax.swing.JMenuItem jMenuItemSrpskiLatinica;
    private javax.swing.JMenu jMenuJezik;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenu menuAngazovanja;
    private javax.swing.JMenuItem menuItemDodajProjekat;
    private javax.swing.JMenuItem menuItemDodajZaposlenog;
    private javax.swing.JMenuItem menuItemIzmeniZaposlenog;
    private javax.swing.JMenuItem menuItemObrisiAngazovanje;
    private javax.swing.JMenuItem menuItemObrisiProjekat;
    private javax.swing.JMenuItem menuItemOdjaviSe;
    private javax.swing.JMenu menuOdjava;
    private javax.swing.JMenu menuProjekti;
    private javax.swing.JMenu menuZaposleni;
    // End of variables declaration//GEN-END:variables
}
