/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.zaposleni;

import domen.Angazovanje;
import domen.OrganizacionaCelina;
import domen.RadnoMesto;
import domen.Zaposleni;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import kontroler.KlijentKontrolerZaposleni;
import modeli.ModelTabeleAngazovanje;
import modeli.ModelTabeleZaposleni;

/**
 *
 * @author Mihajlo
 */
public class IzmeniZaposlenogForma extends javax.swing.JDialog {

    /**
     * Creates new form IzmeniZaposlenogForma
     */
    ModelTabeleZaposleni mtz;
    Zaposleni odabraniZaposleni;
    ModelTabeleAngazovanje mta;
    public IzmeniZaposlenogForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
           initComponents();
           jLabel1.setVisible(false);
           txtZaposleniID.setVisible(false);
           if(lokalizacija.JezikMenadzer.getOdabir() == null){
               lokalizacija.JezikMenadzer.setOdabir("srpski - latinica");
           }
           osveziLokalizaciju();
           setLocationRelativeTo(null);
           setTitle(lokalizacija.JezikMenadzer.get("izmenaIBrisanjeZaposlenog"));
           btnObrisiZaposlenog.setEnabled(false);
           btnIzmeniZaposlenog.setEnabled(false);
           //tblZaposleni.setAutoCreateRowSorter(true);
           mtz = new ModelTabeleZaposleni();
           tblZaposleni.setModel(mtz);
           mta = new ModelTabeleAngazovanje();
           tblAngazovanjaZaposlenih.setModel(mta);
           popuniTabeluSvimZaposlenim(false);
           popuniCmbOrganizacionaCelina();
        } catch (Exception ex) {
            ex.printStackTrace();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPronadjiZaposlenog = new javax.swing.JPanel();
        txtPretragaZaposlenog = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaposleni = new javax.swing.JTable();
        cBoxPrikaziObrisane = new javax.swing.JCheckBox();
        btnPronadjiZaposlenog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnIzmeniZaposlenog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtZaposleniID = new javax.swing.JTextField();
        txtZaposleniIme = new javax.swing.JTextField();
        txtZaposleniPrezime = new javax.swing.JTextField();
        txtZaposleniEmail = new javax.swing.JTextField();
        cmbZaposleniOrganizacionaCelina = new javax.swing.JComboBox<>();
        cmbZaposleniRadnoMesto = new javax.swing.JComboBox<>();
        txtZaposleniDatumZaposlenja = new javax.swing.JFormattedTextField();
        btnObrisiZaposlenog = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAngazovanjaZaposlenih = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPronadjiZaposlenog.setBorder(javax.swing.BorderFactory.createTitledBorder("Pronađi zaposlenog"));

        tblZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZaposleni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblZaposleniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblZaposleni);

        cBoxPrikaziObrisane.setText("Prikaži obrisane");
        cBoxPrikaziObrisane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPrikaziObrisaneActionPerformed(evt);
            }
        });

        btnPronadjiZaposlenog.setText("Pronađi");
        btnPronadjiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiZaposlenogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPronadjiZaposlenogLayout = new javax.swing.GroupLayout(panelPronadjiZaposlenog);
        panelPronadjiZaposlenog.setLayout(panelPronadjiZaposlenogLayout);
        panelPronadjiZaposlenogLayout.setHorizontalGroup(
            panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                        .addComponent(txtPretragaZaposlenog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPronadjiZaposlenog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxPrikaziObrisane)))
                .addContainerGap())
        );
        panelPronadjiZaposlenogLayout.setVerticalGroup(
            panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretragaZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxPrikaziObrisane)
                    .addComponent(btnPronadjiZaposlenog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Učitani zaposleni"));

        btnIzmeniZaposlenog.setText("Izmeni zaposlenog");
        btnIzmeniZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniZaposlenogActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Datum zaposlenja:");

        jLabel6.setText("Organizaciona celina:");

        jLabel7.setText("Radno mesto:");

        txtZaposleniID.setEditable(false);

        txtZaposleniEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZaposleniEmailActionPerformed(evt);
            }
        });

        cmbZaposleniOrganizacionaCelina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbZaposleniOrganizacionaCelinaActionPerformed(evt);
            }
        });

        txtZaposleniDatumZaposlenja.setEditable(false);
        try {
            txtZaposleniDatumZaposlenja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####.")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnObrisiZaposlenog.setText("Obriši zaposlenog");
        btnObrisiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZaposlenogActionPerformed(evt);
            }
        });

        tblAngazovanjaZaposlenih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAngazovanjaZaposlenih);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtZaposleniID)
                                    .addComponent(txtZaposleniIme)
                                    .addComponent(txtZaposleniPrezime)
                                    .addComponent(txtZaposleniEmail)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbZaposleniOrganizacionaCelina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbZaposleniRadnoMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtZaposleniDatumZaposlenja)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisiZaposlenog)
                        .addGap(7, 7, 7)
                        .addComponent(btnIzmeniZaposlenog)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtZaposleniID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtZaposleniIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZaposleniPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtZaposleniEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtZaposleniDatumZaposlenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbZaposleniOrganizacionaCelina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbZaposleniRadnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiZaposlenog)
                    .addComponent(btnIzmeniZaposlenog))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPronadjiZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPronadjiZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPronadjiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiZaposlenogActionPerformed
        try {
            String pretraga = txtPretragaZaposlenog.getText();
            boolean prikaziObrisane = cBoxPrikaziObrisane.isSelected();
            LinkedList<Zaposleni> listaZaposlenihIzPretrage = KlijentKontrolerZaposleni.getInstanca().pronadjiPaVratiZaposlene(pretraga, prikaziObrisane);
            ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
            mtz.setListaZaposlenih(listaZaposlenihIzPretrage);
            LinkedList<Zaposleni> vracenaLista = mtz.vratiListu();
            if(vracenaLista.size() == 0){
                JOptionPane.showMessageDialog(rootPane, lokalizacija.JezikMenadzer.get("neMozeDaNadjeZaposlenog"), lokalizacija.JezikMenadzer.get("neuspesnaPretraga"), JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, lokalizacija.JezikMenadzer.get("nasaoZaposelnog"), lokalizacija.JezikMenadzer.get("uspesnoIzvrseno"), JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnPronadjiZaposlenogActionPerformed

    private void tblZaposleniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblZaposleniMouseClicked
        try{
            int red = tblZaposleni.getSelectedRow();
            if (red == -1) {
                //JOptionPane.showMessageDialog(this, "Odaberite zaposlenog iz tabele.");
            } else {
                ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                odabraniZaposleni = mtz.vratiOdabranogZaposlenog(red);
                Zaposleni ucitaniZaposleni = KlijentKontrolerZaposleni.getInstanca().ucitajZaposlenog(odabraniZaposleni);
                popuniPodatkeUcitanogZaposlenog(ucitaniZaposleni);
                btnIzmeniZaposlenog.setEnabled(true);
                btnObrisiZaposlenog.setEnabled(true);
                if(odabraniZaposleni.getDaLiJeObrisan()){
                    txtZaposleniIme.setEnabled(false);
                    txtZaposleniPrezime.setEnabled(false);
                    txtZaposleniEmail.setEnabled(false);
                    txtZaposleniDatumZaposlenja.setEnabled(false);
                    cmbZaposleniOrganizacionaCelina.setEnabled(false);
                    cmbZaposleniRadnoMesto.setEnabled(false);
                    btnIzmeniZaposlenog.setEnabled(false);
                    btnObrisiZaposlenog.setEnabled(false);
                    tblAngazovanjaZaposlenih.setEnabled(false);
                } else {
                    txtZaposleniIme.setEnabled(true);
                    txtZaposleniPrezime.setEnabled(true);
                    txtZaposleniEmail.setEnabled(true);
                    txtZaposleniDatumZaposlenja.setEnabled(true);
                    cmbZaposleniOrganizacionaCelina.setEnabled(true);
                    cmbZaposleniRadnoMesto.setEnabled(true);
                    btnIzmeniZaposlenog.setEnabled(true);
                    btnObrisiZaposlenog.setEnabled(true);
                    tblAngazovanjaZaposlenih.setEnabled(true);
                }
                JOptionPane.showMessageDialog(rootPane, lokalizacija.JezikMenadzer.get("uspesnoUcitaoZaposlenog"), lokalizacija.JezikMenadzer.get("uspesnoIzvrseno"), JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex){
            try {
                ex.printStackTrace();
                //JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Doslo je do greske!", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(rootPane, "Zaposleni " + odabraniZaposleni + " je obrisan.", "Doslo je do greske.", JOptionPane.INFORMATION_MESSAGE);
                LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene(false);
                if (listaSvihZaposlnih.size() > 0) {
                    ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                    mtz.setListaZaposlenih(listaSvihZaposlnih);
                } else if(listaSvihZaposlnih.size() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Obrisali ste sve zaposlene. Ne postoji nijedan zaposleni za prikaz.");
                    this.dispose();
                }
            } catch (Exception ex1) {
                ex1.printStackTrace();
            }
        }
    }//GEN-LAST:event_tblZaposleniMouseClicked

    private void btnObrisiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZaposlenogActionPerformed
        try {
            KlijentKontrolerZaposleni.getInstanca().obrisiZaposlenog(odabraniZaposleni);
            JOptionPane.showMessageDialog(rootPane, lokalizacija.JezikMenadzer.get("obrisaoZaposlenog") + ": " + odabraniZaposleni, lokalizacija.JezikMenadzer.get("uspesnoIzvrseno"), JOptionPane.INFORMATION_MESSAGE);
            LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene(false);
            if (listaSvihZaposlnih.size() > 0) {
                ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                mtz.setListaZaposlenih(listaSvihZaposlnih);
            } else if(listaSvihZaposlnih.size() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Obrisali ste sve zaposlene. Ne postoji nijedan zaposleni za prikaz.");
                this.dispose();
            }
            txtZaposleniID.setText("");
            txtZaposleniIme.setText("");
            txtZaposleniPrezime.setText("");
            txtZaposleniEmail.setText("");
            txtZaposleniDatumZaposlenja.setText("");
            cmbZaposleniOrganizacionaCelina.setSelectedIndex(0);
            cmbZaposleniRadnoMesto.setSelectedIndex(0);
            btnObrisiZaposlenog.setEnabled(false);
            btnIzmeniZaposlenog.setEnabled(false);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, lokalizacija.JezikMenadzer.get("zaposleni") + " " + odabraniZaposleni + " " + lokalizacija.JezikMenadzer.get("nijeObrisan"), lokalizacija.JezikMenadzer.get("dosloJeDoGreske"), JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(rootPane, "Sistem ne može da obriše zaposlenog.", "Doslo je do greske!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiZaposlenogActionPerformed

    private void cmbZaposleniOrganizacionaCelinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbZaposleniOrganizacionaCelinaActionPerformed
        try {
            OrganizacionaCelina organizacionaCelina = (OrganizacionaCelina) cmbZaposleniOrganizacionaCelina.getSelectedItem();
            popuniCmbRadnoMesto(organizacionaCelina);
        } catch (Exception ex) {
            Logger.getLogger(DodajZaposlenogForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbZaposleniOrganizacionaCelinaActionPerformed

    private void txtZaposleniEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZaposleniEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZaposleniEmailActionPerformed

    private void btnIzmeniZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniZaposlenogActionPerformed
        try {
            Zaposleni izmenjenZaposleni = new Zaposleni();
            if (proveriNovePodatke(izmenjenZaposleni)) {
                KlijentKontrolerZaposleni.getInstanca().izmeniZaposlenog(izmenjenZaposleni);
                JOptionPane.showMessageDialog(rootPane, lokalizacija.JezikMenadzer.get("zapamtioZaposlenog"), lokalizacija.JezikMenadzer.get("uspesnoIzvrseno"), JOptionPane.INFORMATION_MESSAGE);
                LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene(false);
                ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                mtz.setListaZaposlenih(listaSvihZaposlnih);
                btnObrisiZaposlenog.setEnabled(false);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            //JOptionPane.showMessageDialog(rootPane, "Zaposleni " + odabraniZaposleni + " nije izmenjen.", "Doslo je do greske!", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Doslo je do greske!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniZaposlenogActionPerformed

    private void cBoxPrikaziObrisaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPrikaziObrisaneActionPerformed
        try {
            boolean prikaziObrisane = cBoxPrikaziObrisane.isSelected();
            popuniTabeluSvimZaposlenim(prikaziObrisane);
        } catch (Exception ex) {
            Logger.getLogger(IzmeniZaposlenogForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cBoxPrikaziObrisaneActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniZaposlenog;
    private javax.swing.JButton btnObrisiZaposlenog;
    private javax.swing.JButton btnPronadjiZaposlenog;
    private javax.swing.JCheckBox cBoxPrikaziObrisane;
    private javax.swing.JComboBox<Object> cmbZaposleniOrganizacionaCelina;
    private javax.swing.JComboBox<Object> cmbZaposleniRadnoMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPronadjiZaposlenog;
    private javax.swing.JTable tblAngazovanjaZaposlenih;
    private javax.swing.JTable tblZaposleni;
    private javax.swing.JTextField txtPretragaZaposlenog;
    private javax.swing.JFormattedTextField txtZaposleniDatumZaposlenja;
    private javax.swing.JTextField txtZaposleniEmail;
    private javax.swing.JTextField txtZaposleniID;
    private javax.swing.JTextField txtZaposleniIme;
    private javax.swing.JTextField txtZaposleniPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniPodatkeUcitanogZaposlenog(Zaposleni ucitaniZaposleni) throws Exception {
        txtZaposleniID.setText(String.valueOf(ucitaniZaposleni.getZaposleniId()));
        txtZaposleniIme.setText(ucitaniZaposleni.getIme());
        txtZaposleniPrezime.setText(ucitaniZaposleni.getPrezime());
        txtZaposleniEmail.setText(ucitaniZaposleni.getEmail());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        txtZaposleniDatumZaposlenja.setText(sdf.format(ucitaniZaposleni.getDatumZaposlenja()));
        cmbZaposleniOrganizacionaCelina.setSelectedItem(ucitaniZaposleni.getOrganizacionaCelina());
        cmbZaposleniRadnoMesto.setSelectedItem(ucitaniZaposleni.getRadnoMesto());
        LinkedList<Angazovanje> listaAngazovanjaZaZaposlenog = KlijentKontrolerZaposleni.getInstanca().vratiAngazovanjaZaposleog(ucitaniZaposleni);
        if (listaAngazovanjaZaZaposlenog.size() > 0) {
            ModelTabeleAngazovanje mta = (ModelTabeleAngazovanje) tblAngazovanjaZaposlenih.getModel();
            mta.setListaAngazovanje(listaAngazovanjaZaZaposlenog);
        } else {
            mta.setListaAngazovanje(new LinkedList<>());
        }
    }

    private void popuniTabeluSvimZaposlenim(boolean prikaziObrisane) throws Exception {
        LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene(prikaziObrisane);
        if (listaSvihZaposlnih.size() > 0) {
            ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
            mtz.setListaZaposlenih(listaSvihZaposlnih);
        } else if(listaSvihZaposlnih.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ne postoji nijedan zaposleni.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Doslo je do greske prilikom pretrage zaposlenih.");
            this.dispose();
        }
    }

    private void popuniCmbOrganizacionaCelina() throws Exception {
        cmbZaposleniOrganizacionaCelina.removeAllItems();

        LinkedList<OrganizacionaCelina> litsaOrganizacionihCelina = KlijentKontrolerZaposleni.getInstanca().vratiOrganizacioneCeline();
        for (OrganizacionaCelina organizacionaCelina : litsaOrganizacionihCelina) {
            cmbZaposleniOrganizacionaCelina.addItem(organizacionaCelina);
        }
    }

    private void popuniCmbRadnoMesto(OrganizacionaCelina organizacionaCelina) throws Exception {
        cmbZaposleniRadnoMesto.removeAllItems();

        try{
            LinkedList<RadnoMesto> listaRadnihMesta = KlijentKontrolerZaposleni.getInstanca().vratiRadnaMesta(organizacionaCelina);
            for (RadnoMesto radnoMesto : listaRadnihMesta) {
                cmbZaposleniRadnoMesto.addItem(radnoMesto);
            }
        } catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Doslo je do greske!", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private boolean proveriNovePodatke(Zaposleni izmenjenZaposleni) throws Exception {
        izmenjenZaposleni.setZaposleniId(Integer.parseInt(txtZaposleniID.getText()));
        
        String ime = txtZaposleniIme.getText().trim();
            if (ime.isEmpty()) {
                JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("imeNeSmePrazno"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if(!ime.matches("^[A-ZČĆŽŠĐ][a-zčćžšđ]+$")){
                JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("imeNeispravanFormat"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        izmenjenZaposleni.setIme(ime);
        
        String prezime = txtZaposleniPrezime.getText().trim();
            if (prezime.isEmpty()) {
                JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("prezimeNeSmePrazno"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if(!prezime.matches("^[A-ZČĆŽŠĐ][a-zčćžšđ]+$")){
                JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("prezimeNeispravanFormat"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        izmenjenZaposleni.setPrezime(prezime);
        
        String email = txtZaposleniEmail.getText().trim();
            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("emailNeSmePrazno"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if(!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")){
                JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("emailNeispravanFormat"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
            LinkedList<Zaposleni> listaZaposlenih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene(false);
            for (Zaposleni zaposleni : listaZaposlenih) {
                if(zaposleni.getEmail().equals(email) && zaposleni.getZaposleniId() != Integer.parseInt(txtZaposleniID.getText())){
                    JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("vecPostojiIstiMejl"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
        izmenjenZaposleni.setEmail(email);
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        Date datumZaposlenja = sdf.parse(txtZaposleniDatumZaposlenja.getText());
        if(datumZaposlenja.after(new Date())){
            JOptionPane.showMessageDialog(null, lokalizacija.JezikMenadzer.get("datumZaposlenjaNeSmeBuducnost"), lokalizacija.JezikMenadzer.get("greskaPriIzmeniZaposlenog"), JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        izmenjenZaposleni.setDatumZaposlenja(sdf.parse(txtZaposleniDatumZaposlenja.getText()));
        
        izmenjenZaposleni.setOrganizacionaCelina((OrganizacionaCelina) cmbZaposleniOrganizacionaCelina.getSelectedItem());
        
        izmenjenZaposleni.setRadnoMesto((RadnoMesto) cmbZaposleniRadnoMesto.getSelectedItem());
            
        return true;
    }
    
    private void osveziLokalizaciju() {
        javax.swing.border.Border border = panelPronadjiZaposlenog.getBorder();
        if (border instanceof javax.swing.border.TitledBorder) {
            javax.swing.border.TitledBorder titledBorder = (javax.swing.border.TitledBorder) border;
            titledBorder.setTitle(lokalizacija.JezikMenadzer.get("pronadjiZaposlenog"));
            panelPronadjiZaposlenog.repaint();
        }
        javax.swing.border.Border border2 = jPanel1.getBorder();
        if (border2 instanceof javax.swing.border.TitledBorder) {
            javax.swing.border.TitledBorder titledBorder2 = (javax.swing.border.TitledBorder) border2;
            titledBorder2.setTitle(lokalizacija.JezikMenadzer.get("ucitaniZaposleni"));
            jPanel1.repaint();
        }
        btnPronadjiZaposlenog.setText(lokalizacija.JezikMenadzer.get("pronadji"));
        jLabel1.setText(lokalizacija.JezikMenadzer.get("id") + ':');
        jLabel2.setText(lokalizacija.JezikMenadzer.get("ime") + ':');
        jLabel3.setText(lokalizacija.JezikMenadzer.get("prezime") + ':');
        jLabel4.setText(lokalizacija.JezikMenadzer.get("email") + ':');
        jLabel5.setText(lokalizacija.JezikMenadzer.get("datumZaposlenja") + ':');
        jLabel6.setText(lokalizacija.JezikMenadzer.get("organizacionaCelina") + ':');
        jLabel7.setText(lokalizacija.JezikMenadzer.get("radnoMesto") + ':');
        btnObrisiZaposlenog.setText(lokalizacija.JezikMenadzer.get("obrisiZaposlenog"));
        btnIzmeniZaposlenog.setText(lokalizacija.JezikMenadzer.get("izmeniZaposlenog"));
        cBoxPrikaziObrisane.setText(lokalizacija.JezikMenadzer.get("prikaziObrisane"));
        UIManager.put("OptionPane.yesButtonText", lokalizacija.JezikMenadzer.get("da"));
        UIManager.put("OptionPane.noButtonText", lokalizacija.JezikMenadzer.get("ne"));
        UIManager.put("OptionPane.okButtonText", lokalizacija.JezikMenadzer.get("ok"));
        UIManager.put("OptionPane.cancelButtonText", lokalizacija.JezikMenadzer.get("cancel"));
    }
}
